import pyautogui
from time import sleep

sleep(1)
pyautogui.hotkey('win','r')
sleep(1)
pyautogui.write('mspaint', interval=0.1)
sleep(1)
pyautogui.press('enter')
sleep(1)
locate = pyautogui.locateCenterOnScreen('Circulo.png', confidence=0.6)
sleep(1)
print(locate)
sleep(1)
pyautogui.moveTo(locate[0], locate[1])
sleep(1)
pyautogui.click(locate[0], locate[1])
sleep(1)
pyautogui.hotkey('ctrl','1')
sleep(1)
locate = pyautogui.locateCenterOnScreen('PaintCanva.png', confidence=0.5)
sleep(1)
pyautogui.moveTo(locate[0], locate[1])
sleep(1)
pyautogui.click()
sleep(1)
pyautogui.mouseDown(locate[0], locate[1])
sleep(0.1)
pyautogui.moveTo(locate[0] + 500, locate[1] + 500, duration=1)
pyautogui.mouseUp()
sleep(1)
pyautogui.moveTo(locate[0] + 300, locate[1] + 300, duration=1)
sleep(1)
pyautogui.press('alt')
pyautogui.press('t')
pyautogui.press('f')
sleep(1)
pyautogui.press('B')
sleep(1)
pyautogui.click()
